name: cdh-python
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - jupyterlab
  - mystmd
  - ipywidgets
  - numpy
  - pandas
  - xarray
  - zarr>=3.0
  - h5py
  - h5netcdf
  - netCDF4
  - dask
  - scipy
  - matplotlib
  - cartopy
  - hvplot
  - datashader
  - obstore
  - ffmpeg
  - xradar
  - cmweather
  - siphon
  - gcsfs
  - boto3
  - s3fs>=2025.5.1
  - intake-esm
  - xmovie
  - xlrd
  - cmweather
  - pip
  - pip:
      - xmip
      - sodapy
      - pydap
      - git+https://github.com/aladinor/raw2zarr.git
