name: cdh-python
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - jupyterlab
  - jupyter_server
  - mystmd
  - ipywidgets

  # Core scientific stack
  - numpy
  - pandas
  - xarray
  - zarr
  - h5py
  - h5netcdf
  - netCDF4
  - dask
  - scipy
  - matplotlib
  - cartopy
  - hvplot
  - datashader
  - folium
  - ffmpeg

  # Radar & weather
  - xradar
  - cmweather
  - siphon

  # Cloud and intake
  - gcsfs
  - boto3
  - intake-esm

  # Visualization / video
  - xmovie

  # Excel and misc
  - xlrd

  - pip
  - pip:
      - xmip
      - sodapy
      - pydap
