name: atmoscol2023
channels:
  - conda-forge
  - nodefaults
  - pyviz
dependencies:
  - python>=3.9
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - h5netcdf
  - h5py
  - netCDF4
  - xarray
  - cf_xarray
  - xarray-datatree>=0.0.10
  - xarrayutils
  - zarr
  - gcsfs
  - pandas
  - dask
  - arm_pyart
  - matplotlib
  - cartopy
  - hvplot
  - scipy
  - intake-esm
  - xmovie
  - ffmpeg
  - xradar
  - pip
  - xlrd
  - folium
  - boto3
  - datashader
  - ipywidgets
  - pythia-datasets
  - pip:
      - sphinx-pythia-theme
      - pydata-sphinx-theme
      - xmip
      - sodapy