name: publish-book

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    timeout-minutes: 60
    with:
      build_command: myst build --html
      # Also include these to ensure control
      path_to_notebooks: .
      environment_file: environment.yml
      base_url: /${{ github.event.repository.name }}

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
